### ISSUE TITLE
The numpy.zip file downloads but is corrupted.

### ISSUE THREAD

**Issue by ibugueno** [SSIGPRO/PEDRo-Event-Based-Dataset#4] opened 2024-07-28 08:03 UTC
Dear authors,

Thank you very much for this contribution, would it be possible to indicate how to download the numpy.zip file? When I download it manually or through external libraries, it is corrupted

Thank you in advance

**Comment by SageCao1125** [comment] 2024-08-01 14:49
same problem.

**Comment by ChiaraBoretti** [comment] 2024-09-10 13:58
Hello!  
Thank you for your interest in the PEDRo Dataset. We've recently updated to version 2.0, which includes a new numpy.zip folder. Please ensure you download the latest version of the dataset (v2.0) for solving "numpy.zip" folder problems.

**Comment by philippebich** [comment] 2024-10-23 12:50
I have tested the new version of the dataset and I confirm the problem is now solved. I close the issue. Thanks everyone!

**Closed as completed by philippebich** 2024-10-23 12:50 UTC
