### ISSUE TITLE
numpy.zip corrupt?

### ISSUE THREAD

**Issue by agirbau** [SSIGPRO/PEDRo-Event-Based-Dataset#2] opened 2023-12-13 04:44 UTC
Hello!

I'm trying to download the dataset and I get an error when trying to unzip "numpy.zip". I have checked the checksum and it's the same as in the webpage. Maybe it's corrupt somehow?

**Comment by 233AvavAvA** [comment] 2024-07-16 10:44
me too

**Comment by ChiaraBoretti** [comment] 2024-09-10 13:58
Hello!  
Thank you for your interest in the PEDRo Dataset. We've recently updated to version 2.0, which includes a new "numpy.zip" folder. Please ensure you download the latest version of the dataset (v2.0) for solving "numpy.zip" folder problems.

**Comment by philippebich** [comment] 2024-10-23 12:52
I have tested the new version of the dataset and I confirm the problem is now solved. I close the issue. Thanks everyone!

**Closed as completed by philippebich** 2024-10-23 12:52 UTC
